#!/usr/bin/python3

def avgOfNums():
    userList = list(map(int, input().split()))
    total=avg=count= 0
    for i in userList:
        total += i
        count += 1
    avg = total/count
    print(avg)

avgOfNums()
